#!/usr/bin/env python3
"""
BOM2Pic Environment Setup Script
Run this to configure your local development environment
"""

import os
from pathlib import Path

def create_env_file():
    """Create .env file with Supabase credentials"""
    
    env_content = """# BOM2Pic Environment Variables
# Generated by setup script

# File limits
MAX_UPLOAD_MB=20
MAX_IMAGES=0
MAX_FILES=0

# Supabase Configuration
SUPABASE_URL=https://xccxidrokfnyikqrlfrc.supabase.co
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjY3hpZHJva2ZueWlrcXJsZnJjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTM3NDEyMywiZXhwIjoyMDcwOTUwMTIzfQ.mpf2PNIpgu8q9efHwj5LKtJiKpigAuCoivraP28MhJw
SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjY3hpZHJva2ZueWlrcXJsZnJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNzQxMjMsImV4cCI6MjA3MDk1MDEyM30.ZiZhpDdjwURO-c9DxB_9mtL3EYtISkivREKcGhD9oFI
SUPABASE_JWT_SECRET=8SWfhHZTyxCrsA3+/mpmqHEw8jejGA7oGoXPS0kyav6afHAf44h/mzzcYsc6c0hxohefiUtiAmLUBZg42pgq7g==

# PayPal Configuration
PAYPAL_CLIENT_ID=ATv23_KuahdHfUXwXcC55akC6TbAph9EiVNF6aywRTHTyaaCJtagCRwH3nQZQYeyPbSsYUTFWlcjg3FR
PAYPAL_CLIENT_SECRET=EPfmJR2hN7yuilC2-OA3SXz2meMW3IM1_xfQJOHSTQkFhmsFSDKvvmbp0hpHPlQ_YgU3amA7ObPNAihL
PAYPAL_ENVIRONMENT=sandbox
PAYPAL_WEBHOOK_ID=your-paypal-webhook-id

# CORS origins (comma-separated)
ALLOWED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000,https://bom2pic.com
"""

    env_path = Path('.env')
    
    if env_path.exists():
        print("⚠️  .env file already exists!")
        response = input("Do you want to overwrite it? (y/N): ")
        if response.lower() != 'y':
            print("❌ Setup cancelled")
            return False
    
    try:
        with open(env_path, 'w') as f:
            f.write(env_content)
        print("✅ Created .env file with Supabase credentials")
        print("⚠️  TODO: Add your Stripe keys to .env file")
        return True
    except Exception as e:
        print(f"❌ Failed to create .env file: {e}")
        return False

def main():
    print("🚀 BOM2Pic Environment Setup")
    print("=" * 40)
    
    # Create .env file
    if create_env_file():
        print("\n📋 Next Steps:")
        print("1. Run the database_setup.sql in your Supabase SQL Editor")
        print("2. Get Stripe test keys from stripe.com and update .env")
        print("3. Run: python setup_environment.py")
        print("4. Start server: uvicorn app.main:app --reload")
        print("\n🎉 You'll have a working billing system!")
    
if __name__ == "__main__":
    main()
